plugins {
    id 'org.springframework.boot' version '2.7.5'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
    id 'idea'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web:2.7.5'
    implementation 'net.dv8tion:JDA:5.0.0-beta.24'
    implementation 'com.google.guava:guava:33.0.0-jre'

    testImplementation 'org.springframework.boot:spring-boot-starter-test:2.7.5'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.1'

    compileOnly 'org.projectlombok:lombok:1.18.32'
    annotationProcessor 'org.projectlombok:lombok:1.18.32'

    testCompileOnly 'org.projectlombok:lombok:1.18.32'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.32'
}

sourceCompatibility = '17'
targetCompatibility = '17'

compileJava {
    options.encoding = "UTF-8"
}

compileTestJava {
    options.encoding = "UTF-8"
}

repositories {
    mavenCentral()
}

test {
    useJUnitPlatform()
}

jar {
    enabled = false
}

bootJar {
    enabled = true
    archiveBaseName = 'discord-bot'
    archiveVersion = '1.0.0'
}


